### ISSUE TITLE
.Net standard example

### ISSUE THREAD

**Issue by gdodd1977** [loekd/ServiceFabric.ServiceBus#15]
Do you have a demo app for using the .net standard package?  It appears there is a problem with recursive dependencies.

The ServiceBusMessageReceiver relies on IServiceBusCommunicationListener and vice versa. How are you supposed to make these things work together if there is a circular dependency?

**Comment by loekd** [comment]
Please use v6.0.1 and call the [overload] (https://github.com/loekd/ServiceFabric.ServiceBus/blob/NetstandardPackage/ServiceFabric.ServiceBus.Services.Netstd/CommunicationListeners/ServiceBusQueueCommunicationListener.cs#L63) that takes a `Func` that receives the communication listener as an argument and returns the message receiver instance.

Something like this:
``` csharp
var listener = new ServiceBusQueueCommunicationListener(cl => new DefaultServiceBusMessageReceiver(cl, null), serviceContext, serviceBusQueueName, serviceBusSendConnectionString, serviceBusReceiveConnectionString);
```
The other overload will be removed in a future release, because if the mutual dependency. My apologies for that.

Let me know if this helps or not.

**Comment by gdodd1977** [comment]
Yeah. The only issue with this is you can't do this via dependency injection. But that's not exactly earth shattering. Thanks for the quick response!

**Comment by loekd** [comment]
Can't you register `Func<IServiceBusCommunicationListener, IServiceBusMessageReceiver>` in your container?

**Comment by gdodd1977** [comment]
If you register that and register the implementation of IServiceBusMessageReceiver, it gets circular dependency issues.
